version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PSQL_USER=tester
      - PSQL_PASS=tester
      - PSQL_DB=tz_app
      - PSQL_HOST=db
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester
      - POSTGRES_DB=tz_app
